/**
 * Sync i18n catalogs from the source files to the TypeScript modules.
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { CATALOGS, type UiCatalog } from '../src/i18n/catalogs';
import type { Locale } from '../src/locale';

type Dict = Record<string, unknown>;

const CATALOGS_DIR = join(__dirname, '../src/i18n/catalogs');

function isObject(v: unknown): v is Dict {
  return Object.prototype.toString.call(v) === '[object Object]';
}

function merge<T extends Dict, S extends Dict>(current: T, en: S): T & S {
  return Object.fromEntries(
    Object.entries(en).map(([key, value]) => {
      if (isObject(value)) return [key, merge(current[key] as Dict, value)];
      if (Object.hasOwn(current, key)) return [key, current[key]];
      return [key, `${value} [EN]`];
    }),
  ) as T & S;
}

function sortObject(obj: Dict): Dict {
  return Object.fromEntries(
    Object.entries(obj)
      .map(([k, v]) => [k, isObject(v) ? sortObject(v) : v] as const)
      .sort(([a], [b]) => a.localeCompare(b)),
  );
}

async function writeModule(
  modulePath: string,
  exportName: string,
  catalog: UiCatalog,
) {
  const [moduleName] = modulePath.match(/\/([a-z]+)$/)?.[0] ?? [];
  const header =
    moduleName === 'en'
      ? `/**
 * This file is the source of truth for the English catalog.
 * It is used to generate the other catalogs.
 */
`
      : `/**
 * This file is auto-generated by the sync-i18n.ts script.
 * Do not edit it manually.
 */
`;
  await writeFile(
    `${modulePath}.ts`,
    `${header}\n\nexport const ${exportName} = ${JSON.stringify(sortObject(catalog), null, 2)};\n`,
  );
}

async function loadCatalog(lang: Locale) {
  const modulePath = join(CATALOGS_DIR, lang);
  const targetModule: Record<string, UiCatalog> = await import(modulePath);
  const [exportName, targetCatalog] =
    Object.entries(targetModule).find(([, v]) => isObject(v)) ?? [];
  if (!exportName || !targetCatalog) {
    throw new Error(`No export name or target catalog found in ${lang}`);
  }
  return { exportName, targetCatalog };
}

async function enToLang(lang: Locale) {
  const { exportName, targetCatalog } = await loadCatalog(lang);
  const mergedCatalog = merge(targetCatalog, CATALOGS.en);
  await writeModule(join(CATALOGS_DIR, lang), exportName, mergedCatalog);
}

async function rewriteEn() {
  const { exportName, targetCatalog } = await loadCatalog('en');
  await writeModule(join(CATALOGS_DIR, 'en'), exportName, targetCatalog);
}

async function main() {
  await rewriteEn();

  await Promise.all(
    Object.keys(CATALOGS)
      .filter((lang) => lang !== 'en')
      .map((lang) => enToLang(lang as Locale)),
  );
}

main().then(() => {
  console.log('finished');
}, console.error);
